// Code generated by ogen, DO NOT EDIT.

package weather_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetWeatherByCity implements GetWeatherByCity operation.
//
// Get weather data for a city.
//
// GET /api/v1/weather/{city}
func (UnimplementedHandler) GetWeatherByCity(ctx context.Context, params GetWeatherByCityParams) (r GetWeatherByCityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWeatherByCity implements UpdateWeatherByCity operation.
//
// Update or create weather data for a city.
//
// PUT /api/v1/weather/{city}
func (UnimplementedHandler) UpdateWeatherByCity(ctx context.Context, req *UpdateWeatherRequest, params UpdateWeatherByCityParams) (r UpdateWeatherByCityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
