// Code generated by ogen, DO NOT EDIT.

package weather_v1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetWeatherByCityParams is parameters of GetWeatherByCity operation.
type GetWeatherByCityParams struct {
	// Название города, для которого запрашиваются или
	// обновляются данные о погоде.
	City string
}

func unpackGetWeatherByCityParams(packed middleware.Parameters) (params GetWeatherByCityParams) {
	{
		key := middleware.ParameterKey{
			Name: "city",
			In:   "path",
		}
		params.City = packed[key].(string)
	}
	return params
}

func decodeGetWeatherByCityParams(args [1]string, argsEscaped bool, r *http.Request) (params GetWeatherByCityParams, _ error) {
	// Decode path: city.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "city",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.City = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    100,
					MaxLengthSet: true,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.City)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "city",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateWeatherByCityParams is parameters of UpdateWeatherByCity operation.
type UpdateWeatherByCityParams struct {
	// Название города, для которого запрашиваются или
	// обновляются данные о погоде.
	City string
}

func unpackUpdateWeatherByCityParams(packed middleware.Parameters) (params UpdateWeatherByCityParams) {
	{
		key := middleware.ParameterKey{
			Name: "city",
			In:   "path",
		}
		params.City = packed[key].(string)
	}
	return params
}

func decodeUpdateWeatherByCityParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateWeatherByCityParams, _ error) {
	// Decode path: city.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "city",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.City = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    100,
					MaxLengthSet: true,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.City)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "city",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
