// Code generated by ogen, DO NOT EDIT.

package weather_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetWeatherByCity implements GetWeatherByCity operation.
	//
	// Get weather data for a city.
	//
	// GET /api/v1/weather/{city}
	GetWeatherByCity(ctx context.Context, params GetWeatherByCityParams) (GetWeatherByCityRes, error)
	// UpdateWeatherByCity implements UpdateWeatherByCity operation.
	//
	// Update or create weather data for a city.
	//
	// PUT /api/v1/weather/{city}
	UpdateWeatherByCity(ctx context.Context, req *UpdateWeatherRequest, params UpdateWeatherByCityParams) (UpdateWeatherByCityRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
