// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ufo/v1/ufo.proto

package ufo_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SightingInfo базовая информация о наблюдении НЛО
type SightingInfo struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	ObservedAt      *timestamppb.Timestamp  `protobuf:"bytes,1,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Location        string                  `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`                                      // обязаловка
	Description     string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                // обязаловка
	Color           *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`                                            // Опционально
	Sound           *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=sound,proto3" json:"sound,omitempty"`                                            // Опционально
	DurationSeconds *wrapperspb.Int32Value  `protobuf:"bytes,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // Продолжительность наблюдения в секундах (опционально)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SightingInfo) Reset() {
	*x = SightingInfo{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SightingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SightingInfo) ProtoMessage() {}

func (x *SightingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SightingInfo.ProtoReflect.Descriptor instead.
func (*SightingInfo) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{0}
}

func (x *SightingInfo) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *SightingInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SightingInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SightingInfo) GetColor() *wrapperspb.StringValue {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *SightingInfo) GetSound() *wrapperspb.StringValue {
	if x != nil {
		return x.Sound
	}
	return nil
}

func (x *SightingInfo) GetDurationSeconds() *wrapperspb.Int32Value {
	if x != nil {
		return x.DurationSeconds
	}
	return nil
}

type SightingUpdateInfo struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	ObservedAt      *timestamppb.Timestamp  `protobuf:"bytes,1,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Location        *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`                                      // обязаловка
	Description     *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                // обязаловка
	Color           *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`                                            // Опционально
	Sound           *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=sound,proto3" json:"sound,omitempty"`                                            // Опционально
	DurationSeconds *wrapperspb.Int32Value  `protobuf:"bytes,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // Продолжительность наблюдения в секундах (опционально)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SightingUpdateInfo) Reset() {
	*x = SightingUpdateInfo{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SightingUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SightingUpdateInfo) ProtoMessage() {}

func (x *SightingUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SightingUpdateInfo.ProtoReflect.Descriptor instead.
func (*SightingUpdateInfo) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{1}
}

func (x *SightingUpdateInfo) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *SightingUpdateInfo) GetLocation() *wrapperspb.StringValue {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *SightingUpdateInfo) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *SightingUpdateInfo) GetColor() *wrapperspb.StringValue {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *SightingUpdateInfo) GetSound() *wrapperspb.StringValue {
	if x != nil {
		return x.Sound
	}
	return nil
}

func (x *SightingUpdateInfo) GetDurationSeconds() *wrapperspb.Int32Value {
	if x != nil {
		return x.DurationSeconds
	}
	return nil
}

type Sighting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid уникальный идентификатор наблюдения
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Общая информация о наблюдении
	Info *SightingInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// created_at время создания записи
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at время последнего обновления записи
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// deleted_at время удаления записи (опционально)
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sighting) Reset() {
	*x = Sighting{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sighting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sighting) ProtoMessage() {}

func (x *Sighting) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sighting.ProtoReflect.Descriptor instead.
func (*Sighting) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{2}
}

func (x *Sighting) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Sighting) GetInfo() *SightingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Sighting) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Sighting) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Sighting) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *SightingInfo          `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetInfo() *SightingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{4}
}

func (x *CreateResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sighting      *Sighting              `protobuf:"bytes,1,opt,name=sighting,proto3" json:"sighting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetSighting() *Sighting {
	if x != nil {
		return x.Sighting
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UpdateInfo    *SightingUpdateInfo    `protobuf:"bytes,2,opt,name=update_info,json=updateInfo,proto3" json:"update_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRequest) GetUpdateInfo() *SightingUpdateInfo {
	if x != nil {
		return x.UpdateInfo
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_ufo_v1_ufo_proto protoreflect.FileDescriptor

const file_ufo_v1_ufo_proto_rawDesc = "" +
	"\n" +
	"\x10ufo/v1/ufo.proto\x12\x06ufo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb9\x02\n" +
	"\fSightingInfo\x12;\n" +
	"\vobserved_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\x05color\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05color\x122\n" +
	"\x05sound\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05sound\x12F\n" +
	"\x10duration_seconds\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fdurationSeconds\"\xfb\x02\n" +
	"\x12SightingUpdateInfo\x12;\n" +
	"\vobserved_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x128\n" +
	"\blocation\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\blocation\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x122\n" +
	"\x05color\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05color\x122\n" +
	"\x05sound\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05sound\x12F\n" +
	"\x10duration_seconds\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fdurationSeconds\"\xf9\x01\n" +
	"\bSighting\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12(\n" +
	"\x04info\x18\x02 \x01(\v2\x14.ufo.v1.SightingInfoR\x04info\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"9\n" +
	"\rCreateRequest\x12(\n" +
	"\x04info\x18\x01 \x01(\v2\x14.ufo.v1.SightingInfoR\x04info\"$\n" +
	"\x0eCreateResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\";\n" +
	"\vGetResponse\x12,\n" +
	"\bsighting\x18\x01 \x01(\v2\x10.ufo.v1.SightingR\bsighting\"`\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12;\n" +
	"\vupdate_info\x18\x02 \x01(\v2\x1a.ufo.v1.SightingUpdateInfoR\n" +
	"updateInfo\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid2\xe7\x01\n" +
	"\n" +
	"UFOService\x127\n" +
	"\x06Create\x12\x15.ufo.v1.CreateRequest\x1a\x16.ufo.v1.CreateResponse\x12.\n" +
	"\x03Get\x12\x12.ufo.v1.GetRequest\x1a\x13.ufo.v1.GetResponse\x127\n" +
	"\x06Update\x12\x15.ufo.v1.UpdateRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x06Delete\x12\x15.ufo.v1.DeleteRequest\x1a\x16.google.protobuf.EmptyBBZ@github.com/yyunoshev/yyunoshev_go/week1/grpc/proto/ufo/v1;ufo_v1b\x06proto3"

var (
	file_ufo_v1_ufo_proto_rawDescOnce sync.Once
	file_ufo_v1_ufo_proto_rawDescData []byte
)

func file_ufo_v1_ufo_proto_rawDescGZIP() []byte {
	file_ufo_v1_ufo_proto_rawDescOnce.Do(func() {
		file_ufo_v1_ufo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ufo_v1_ufo_proto_rawDesc), len(file_ufo_v1_ufo_proto_rawDesc)))
	})
	return file_ufo_v1_ufo_proto_rawDescData
}

var file_ufo_v1_ufo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ufo_v1_ufo_proto_goTypes = []any{
	(*SightingInfo)(nil),           // 0: ufo.v1.SightingInfo
	(*SightingUpdateInfo)(nil),     // 1: ufo.v1.SightingUpdateInfo
	(*Sighting)(nil),               // 2: ufo.v1.Sighting
	(*CreateRequest)(nil),          // 3: ufo.v1.CreateRequest
	(*CreateResponse)(nil),         // 4: ufo.v1.CreateResponse
	(*GetRequest)(nil),             // 5: ufo.v1.GetRequest
	(*GetResponse)(nil),            // 6: ufo.v1.GetResponse
	(*UpdateRequest)(nil),          // 7: ufo.v1.UpdateRequest
	(*DeleteRequest)(nil),          // 8: ufo.v1.DeleteRequest
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),  // 11: google.protobuf.Int32Value
	(*emptypb.Empty)(nil),          // 12: google.protobuf.Empty
}
var file_ufo_v1_ufo_proto_depIdxs = []int32{
	9,  // 0: ufo.v1.SightingInfo.observed_at:type_name -> google.protobuf.Timestamp
	10, // 1: ufo.v1.SightingInfo.color:type_name -> google.protobuf.StringValue
	10, // 2: ufo.v1.SightingInfo.sound:type_name -> google.protobuf.StringValue
	11, // 3: ufo.v1.SightingInfo.duration_seconds:type_name -> google.protobuf.Int32Value
	9,  // 4: ufo.v1.SightingUpdateInfo.observed_at:type_name -> google.protobuf.Timestamp
	10, // 5: ufo.v1.SightingUpdateInfo.location:type_name -> google.protobuf.StringValue
	10, // 6: ufo.v1.SightingUpdateInfo.description:type_name -> google.protobuf.StringValue
	10, // 7: ufo.v1.SightingUpdateInfo.color:type_name -> google.protobuf.StringValue
	10, // 8: ufo.v1.SightingUpdateInfo.sound:type_name -> google.protobuf.StringValue
	11, // 9: ufo.v1.SightingUpdateInfo.duration_seconds:type_name -> google.protobuf.Int32Value
	0,  // 10: ufo.v1.Sighting.info:type_name -> ufo.v1.SightingInfo
	9,  // 11: ufo.v1.Sighting.created_at:type_name -> google.protobuf.Timestamp
	9,  // 12: ufo.v1.Sighting.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 13: ufo.v1.Sighting.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 14: ufo.v1.CreateRequest.info:type_name -> ufo.v1.SightingInfo
	2,  // 15: ufo.v1.GetResponse.sighting:type_name -> ufo.v1.Sighting
	1,  // 16: ufo.v1.UpdateRequest.update_info:type_name -> ufo.v1.SightingUpdateInfo
	3,  // 17: ufo.v1.UFOService.Create:input_type -> ufo.v1.CreateRequest
	5,  // 18: ufo.v1.UFOService.Get:input_type -> ufo.v1.GetRequest
	7,  // 19: ufo.v1.UFOService.Update:input_type -> ufo.v1.UpdateRequest
	8,  // 20: ufo.v1.UFOService.Delete:input_type -> ufo.v1.DeleteRequest
	4,  // 21: ufo.v1.UFOService.Create:output_type -> ufo.v1.CreateResponse
	6,  // 22: ufo.v1.UFOService.Get:output_type -> ufo.v1.GetResponse
	12, // 23: ufo.v1.UFOService.Update:output_type -> google.protobuf.Empty
	12, // 24: ufo.v1.UFOService.Delete:output_type -> google.protobuf.Empty
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_ufo_v1_ufo_proto_init() }
func file_ufo_v1_ufo_proto_init() {
	if File_ufo_v1_ufo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ufo_v1_ufo_proto_rawDesc), len(file_ufo_v1_ufo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ufo_v1_ufo_proto_goTypes,
		DependencyIndexes: file_ufo_v1_ufo_proto_depIdxs,
		MessageInfos:      file_ufo_v1_ufo_proto_msgTypes,
	}.Build()
	File_ufo_v1_ufo_proto = out.File
	file_ufo_v1_ufo_proto_goTypes = nil
	file_ufo_v1_ufo_proto_depIdxs = nil
}
